// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tiC_hhfi60yU70tt1Fnnt1wHcWvbUVA',
    appId: '1:759767319524:web:019076827dc948bd373df1',
    messagingSenderId: '759767319524',
    projectId: 'iou-flutter',
    authDomain: 'iou-flutter.firebaseapp.com',
    storageBucket: 'iou-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAgxeosCeDhWBhMohOFyy3c7BiBGf5IU',
    appId: '1:759767319524:android:cf1cdd50e5371574373df1',
    messagingSenderId: '759767319524',
    projectId: 'iou-flutter',
    storageBucket: 'iou-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjDaKe8ReFIvMQDew7CZWbGtK_IVVyJH8',
    appId: '1:759767319524:ios:f60ed579cad2d1d9373df1',
    messagingSenderId: '759767319524',
    projectId: 'iou-flutter',
    storageBucket: 'iou-flutter.firebasestorage.app',
    iosBundleId: 'com.jaysheth.iouFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjDaKe8ReFIvMQDew7CZWbGtK_IVVyJH8',
    appId: '1:759767319524:ios:f60ed579cad2d1d9373df1',
    messagingSenderId: '759767319524',
    projectId: 'iou-flutter',
    storageBucket: 'iou-flutter.firebasestorage.app',
    iosBundleId: 'com.jaysheth.iouFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tiC_hhfi60yU70tt1Fnnt1wHcWvbUVA',
    appId: '1:759767319524:web:06c2faa24a9c7839373df1',
    messagingSenderId: '759767319524',
    projectId: 'iou-flutter',
    authDomain: 'iou-flutter.firebaseapp.com',
    storageBucket: 'iou-flutter.firebasestorage.app',
  );
}
